version: '3'

volumes:
  mysql_data:
    driver: local

services:
  idp:
    image: jboss/keycloak
    container_name: keycloak
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: mysql
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_VENDOR: MYSQL
      JDBC_PARAMS: 'autoReconnect=true&useSSL=false'
    ports:
      - 8080:8080
    networks:
      - front-nw
      - back-nw
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: root
    networks:
      - back-nw
      
networks:
  front-nw:
    driver: bridge
  back-nw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.168.0/24
