version: '3'

services:
  terraform:
    image: hashicorp/terraform:0.12.3
    volumes:
      - ${credential_path}:/home
      - ./:/workdir
    working_dir: "/workdir"
    environment:
      - GOOGLE_CLOUD_KEYFILE_JSON=${credential_file}

